Repository janoamaral/tokyo-night-tmux, pull requests merged in 2024-01, with the labels that each got.

#23 fix #22
  tokyo-night.tmux
Labels: bug

#28 Added more documentation about what fonts to use for this theme
  README.md
Labels: documentation

#29 Added missing Tokyo Night highlighting color
  tokyo-night.tmux
Labels: enhancement

#32 Fixed bug report & security report templates text
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/security_report.md
Labels: bug

#33 fix: #30
  tokyo-night.tmux
Labels: bug

#39 Added variables to pick styles for window,pane and zoom numbers
  src/custom-number.sh
  tokyo-night.tmux
Labels: enhancement

#35 Implement support for nowplaying-cli
  README.md
  src/cmus-tmux-statusbar.sh
  src/music-tmux-statusbar.sh
  tokyo-night.tmux
Labels: enhancement

#40 Updated shell scripts to all use hashbang /usr/bin/env bash
  src/custom-number.sh
  src/git-status.sh
  src/music-tmux-statusbar.sh
  src/wb-git-status.sh
Labels: bug
