Repository janoamaral/tokyo-night-tmux, pull requests merged in 2024-04, with the labels that each got.

#57 added current working directory / current pane path
  README.md
  src/path-widget.sh
  tokyo-night.tmux
Labels: enhancement

#58 fix duplicates
  README.md
Labels: bug, documentation

#60 v1.5-rc2
  README.md
  src/datetime-widget.sh
  src/git-status.sh
  src/music-tmux-statusbar.sh
  src/netspeed.sh
  src/path-widget.sh
  src/themes.sh
  src/wb-git-status.sh
  tokyo-night.tmux
Labels: beta

#59 Added Battery Widget
  README.md
  src/battery-widget.sh
  tokyo-night.tmux
Labels: enhancement

#65 v1.5
  src/battery-widget.sh
  src/datetime-widget.sh
  src/git-status.sh
  src/music-tmux-statusbar.sh
  src/netspeed.sh
  src/themes.sh
  src/wb-git-status.sh
  tokyo-night.tmux
Labels: 🚀 Release

#63 macOS support improvements
  README.md
  lib/coreutils-compat.sh
  src/battery-widget.sh
  src/cmus-tmux-statusbar.sh
  src/custom-number.sh
  src/datetime-widget.sh
  src/git-status.sh
  src/music-tmux-statusbar.sh
  src/netspeed.sh
  src/path-widget.sh
  src/themes.sh
  src/wb-git-status.sh
Labels: enhancement

#69 fix: wrong git sync icon background color
  src/git-status.sh
Labels: bug

#70 Implement BATS workflow
  .github/workflows/bats.yml
  .github/workflows/pre-commit.yml
  .github/workflows/report.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  src/wb-git-status.sh
  test/stub.bats
Labels: enhancement
